spring:
  application:
    name: studfolio

  datasource:
    url: jdbc:postgresql://localhost:5432/studfolio_db
    username: studfolio_user
    password: studfolio123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
